[package]
org = "ballerina"
name = "websubhub"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["websub", "hub", "publisher", "service", "listener", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-websubhub"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.4.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "websubhub-native"
version = "@toml.version@"
path = "../native/build/libs/websubhub-native-@project.version@.jar"
