[package]
org = "ballerina"
name = "websubhub"
version = "1.0.2"
authors = ["Ballerina"]
keywords = ["websub", "hub", "publisher", "service", "listener", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-websubhub"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/websubhub-native-1.0.2-SNAPSHOT.jar"
