[package]
org = "ballerina"
name = "websubhub"
version = "1.10.0"
authors = ["Ballerina"]
keywords = ["websub", "hub", "publisher", "service", "listener", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-websubhub"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "websubhub-native"
version = "1.10.0"
path = "../native/build/libs/websubhub-native-1.10.0-SNAPSHOT.jar"
