[container.image]
repository="anuruddhal"
name="kafka"
tag="v1"

[[container.copy.files]]
sourceFile="./resources/server.crt"
target="/home/ballerina/resources/server.crt"

[[container.copy.files]]
sourceFile="./resources/server.key"
target="/home/ballerina/resources/server.key"

[[container.copy.files]]
sourceFile="./Config.toml"
target="/home/ballerina/Config.toml"

[[cloud.config.files]]
file="./resources/server.key"
mount_path="/home/ballerina/resorces/server.key"

[[cloud.config.files]]
file="./resources/server.crt"
mount_path="/home/ballerina/resorces/server.crt"

[[cloud.config.files]]
file="./Config.toml"
